[terminal]
vt = 1

[default_session]
command = "tuigreet --background matrix --matrix-colors '#7dcfff,#7aa2f7,#bb9af7' --matrix-length 6,20 --theme 'border=lightblue;title=lightblue;text=white;time=lightblue;greet=lightmagenta;prompt=lightcyan;input=white;action=darkgray;button=lightmagenta;container=black' --time --time-format '%A %d %B  ·  %H:%M' --greeting 'xynogamer' --greet-align center --asterisks --asterisks-char '•' --remember --remember-session --user-menu --user-menu-min-uid 1000 --window-padding 2 --container-padding 2 --prompt-padding 1 --width 60 --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' --cmd start-hyprland"
user = "greeter"
